services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-notionclone}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  minio-init:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set minio http://minio:9000 ${MINIO_ROOT_USER:-minioadmin} ${MINIO_ROOT_PASSWORD:-minioadmin};
      mc mb minio/${MINIO_BUCKET_NAME:-notionclone-uploads} --ignore-existing;
      mc anonymous set download minio/${MINIO_BUCKET_NAME:-notionclone-uploads};
      exit 0;
      "

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    expose:
      - "8081"
    labels:
      - "traefik.http.services.backend.loadbalancer.server.port=8081"
      # Disable buffering for SSE endpoints
      - "traefik.http.middlewares.sse-headers.headers.customresponseheaders.X-Accel-Buffering=no"
      - "traefik.http.middlewares.sse-headers.headers.customresponseheaders.Cache-Control=no-cache"
      - "traefik.http.middlewares.sse-headers.buffering.retryExpression=IsNetworkError() && Attempts() < 2"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      ASPNETCORE_URLS: "http://0.0.0.0:8081"
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=${POSTGRES_DB:-notionclone};Username=${POSTGRES_USER:-postgres};Password=${POSTGRES_PASSWORD:-postgres}"
      ConnectionStrings__Redis: "redis:6379"
      MinIO__Endpoint: "minio:9000"
      MinIO__AccessKey: ${MINIO_ROOT_USER:-minioadmin}
      MinIO__SecretKey: ${MINIO_ROOT_PASSWORD:-minioadmin}
      MinIO__BucketName: ${MINIO_BUCKET_NAME:-notionclone-uploads}
      MinIO__UseSSL: "false"
      Jwt__SecretKey: ${JWT_SECRET_KEY}
      Jwt__Issuer: ${JWT_ISSUER:-NotionClone}
      Jwt__Audience: ${JWT_AUDIENCE:-NotionCloneUsers}
      Jwt__ExpiryMinutes: ${JWT_EXPIRY_MINUTES:-60}
      Cors__AllowedOrigins__0: ${CORS_ALLOWED_ORIGINS}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-https://api.notion.dutchcaz.com}
    ports:
      - "3000:8080"
    expose:
      - "8080"
    labels:
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  minio_data:
